# This is a basic workflow to help you get started with Actions

name: Simple Usage

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: xu-cheng/latex-action@v2
        with:
         root_file: "*.tex"
         glob_root_file: true
